# Generated by Django 3.2.4 on 2021-06-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('nickname', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
