# Generated by Django 3.2.6 on 2021-08-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_user'),
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
