# Generated by Django 3.2.6 on 2021-08-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=40)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
